#!/usr/bin/env bash
# 
IFS=':'

# Read the /etc/passwd file line by line
while read -r username _ user_id group_id home_directory shell _; do
    # Print the formatted story
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
