#!/usr/bin/env bash
# This script prints "Best School" 10 times, and on the 9th iteration, it adds "Hi" on a new line.

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
